#!/usr/bin/env node
// Build the kit into dist/<version>/.
//
//   node tools/build.mjs [--tokens PATH] [--out DIR] [--check]
//
// From meridian-design/brand/tokens.json (--tokens, default
// ../meridian-design/brand/tokens.json) it generates the brand's tokens
// (generated/tokens.css: spacing, radii, shadows, type) and the brand default
// scheme (generated/schemes/default.css: the contract's colour properties,
// light and dark). Both are committed, because meridian-design is private and
// whoever builds the kit without it (CI, the dashboard's image) builds from
// them; check-brand reads them too. --check regenerates in memory and fails
// when the committed files are stale, and is what `make check-tokens` runs.
//
// Then it assembles dist/<version>/: meridian.css (the default scheme as a
// cascade layer, the tokens, the base and component CSS), meridian.js and its
// modules, the schemes (the default, and every sample in schemes/*.json,
// each held to the contract), scheme-contract.json (the manifest of what a
// scheme defines and the pairs it must pass) and the gallery.

import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, existsSync, copyFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { brandScheme, parseSchemeCss, renderSchemeCss, validSchemeId } from "../src/lib/scheme.js";
import { checkScheme } from "../src/lib/contrast.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT_TOKENS = resolve(ROOT, "../meridian-design/brand/tokens.json");

// Which rules each of the brand's type styles sets. Public-page styles
// (display, section-title) are the public page's and not the kit's.
export const TYPE_SELECTORS = {
  "page-title": "h1, .om-page-title",
  "section-heading": "h2, .om-section-heading",
  body: "body",
  small: "small, .hint, .faint",
  badge: ".badge, .pill",
  label: "th, .label",
  code: "code, kbd, samp, .mono",
};

const GENERATED_NOTE = (what) =>
  `/* Generated by tools/build.mjs from meridian-design/brand/tokens.json: ${what}.\n` +
  ` * Do not edit; change the token and run \`make tokens\`. make check-tokens and\n` +
  ` * meridian-design's check-brand hold this file to the tokens. */\n`;

function tokenValue(t, mode) {
  return typeof t.value === "string" ? t.value : t.value[mode];
}

/** generated/tokens.css: everything of the brand's that is not a colour. */
export function renderTokensCss(tokens) {
  const light = [];
  const dark = [];
  for (const family of ["spacing", "radius", "shadow"]) {
    for (const t of tokens[family].tokens) {
      light.push(`    --${t.name}: ${tokenValue(t, "light")};`);
      if (tokenValue(t, "dark") !== tokenValue(t, "light")) dark.push(`--${t.name}: ${tokenValue(t, "dark")};`);
    }
  }
  light.push(`    --sans: ${tokens.type.families.sans};`);
  light.push(`    --mono: ${tokens.type.families.mono};`);
  const darkBlock = (sel, indent) =>
    `${indent}${sel} {\n${dark.map((d) => `${indent}  ${d}`).join("\n")}\n${indent}}`;

  const styles = new Map();
  for (const g of tokens.type.groups) for (const s of g.styles) styles.set(s.name, { ...s, family: g.family });
  const rules = [];
  for (const [name, selector] of Object.entries(TYPE_SELECTORS)) {
    const s = styles.get(name);
    if (!s) throw new Error(`tokens.json has no type style "${name}"`);
    const decl = [
      `font-family: var(--${s.family});`,
      `font-size: ${s.fontSize};`,
      `line-height: ${s.lineHeight};`,
      `font-weight: ${s.fontWeight};`,
    ];
    if (s.letterSpacing) decl.push(`letter-spacing: ${s.letterSpacing};`);
    rules.push(`  /* ${name}: ${s.usage} */\n  ${selector} { ${decl.join(" ")} }`);
  }

  return (
    GENERATED_NOTE("spacing, radii, shadows and type") +
    "@layer meridian.tokens {\n" +
    `  :root {\n${light.join("\n")}\n  }\n\n` +
    "  @media (prefers-color-scheme: dark) {\n" +
    darkBlock(':root:not([data-om-mode="light"])', "    ") +
    "\n  }\n\n" +
    darkBlock(':root[data-om-mode="dark"]', "  ") +
    "\n\n  /* The page follows the mode the frame hands it: native controls and\n" +
    "   * scrollbars too. No attribute (or \"system\") follows the system. */\n" +
    "  :root { color-scheme: light dark; }\n" +
    '  :root[data-om-mode="light"] { color-scheme: light; }\n' +
    '  :root[data-om-mode="dark"] { color-scheme: dark; }\n' +
    "}\n\n" +
    "@layer meridian.base {\n" +
    rules.join("\n") +
    "\n}\n"
  );
}

/** generated/schemes/default.css: the brand default scheme. */
export function renderDefaultScheme(tokens, contract) {
  const scheme = brandScheme(tokens, contract);
  const css = renderSchemeCss("default", scheme, contract).replace(/^/, GENERATED_NOTE("the brand default colour scheme"));
  return { scheme, css };
}

function generate(tokensPath, contract) {
  const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));
  const { scheme, css } = renderDefaultScheme(tokens, contract);
  return {
    scheme,
    files: {
      "generated/tokens.css": renderTokensCss(tokens),
      "generated/schemes/default.css": css,
    },
  };
}

function args(argv) {
  const out = { tokens: null, out: join(ROOT, "dist"), check: false };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--tokens") out.tokens = resolve(argv[++i]);
    else if (argv[i] === "--out") out.out = resolve(argv[++i]);
    else if (argv[i] === "--check") out.check = true;
    else throw new Error(`unknown argument ${argv[i]}; usage: build.mjs [--tokens PATH] [--out DIR] [--check]`);
  }
  return out;
}

function write(path, text) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
}

function copyDir(from, to, filter = () => true) {
  mkdirSync(to, { recursive: true });
  for (const f of readdirSync(from).sort()) if (filter(f)) copyFileSync(join(from, f), join(to, f));
}

function fail(message) {
  console.error(`build FAILED: ${message}`);
  process.exit(1);
}

function main() {
  const opts = args(process.argv.slice(2));
  const contract = JSON.parse(readFileSync(join(ROOT, "contract/scheme.json"), "utf8"));
  const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
  const version = pkg.version;
  const tokensPath = opts.tokens || DEFAULT_TOKENS;

  if (!existsSync(tokensPath)) {
    if (opts.tokens) fail(`no tokens at ${tokensPath}`);
    if (opts.check) {
      console.log(`check-tokens: skipped, no tokens at ${tokensPath} (meridian-design is private; CI builds from generated/)`);
      return;
    }
    console.log(`build: no tokens at ${tokensPath}; building from the committed generated/`);
  } else {
    const { files } = generate(tokensPath, contract);
    if (opts.check) {
      const stale = Object.entries(files).filter(([p, text]) => {
        const path = join(ROOT, p);
        return !existsSync(path) || readFileSync(path, "utf8") !== text;
      });
      if (stale.length) fail(`${stale.map(([p]) => p).join(", ")} differ from ${tokensPath}; run \`make tokens\``);
      console.log(`check-tokens OK: generated/ matches ${tokensPath}`);
      return;
    }
    for (const [p, text] of Object.entries(files)) write(join(ROOT, p), text);
  }

  const read = (p) => readFileSync(join(ROOT, p), "utf8");
  const defaultCss = read("generated/schemes/default.css");
  const out = join(opts.out, version);
  rmSync(out, { recursive: true, force: true });

  // Every scheme the kit ships is held to the contract before it is written.
  const parsed = parseSchemeCss(defaultCss, contract);
  const checked = checkScheme(parsed.scheme, contract);
  if (parsed.problems.length || !checked.ok) {
    fail(`the brand default scheme fails the contract:\n  ${[...parsed.problems, ...checked.problems].join("\n  ")}`);
  }
  write(join(out, "schemes/default.css"), defaultCss);
  const samples = existsSync(join(ROOT, "schemes"))
    ? readdirSync(join(ROOT, "schemes")).filter((f) => f.endsWith(".json")).sort()
    : [];
  const shipped = [{ id: "default", name: "Open Meridian" }];
  for (const f of samples) {
    const s = JSON.parse(read(`schemes/${f}`));
    if (!validSchemeId(s.id) || s.id === "default") fail(`schemes/${f}: "${s.id}" is not a usable scheme id`);
    const result = checkScheme(s, contract);
    if (!result.ok) fail(`schemes/${f} fails the contract:\n  ${result.problems.join("\n  ")}`);
    write(join(out, `schemes/${s.id}.css`), renderSchemeCss(s.id, s, contract, `Colour scheme "${s.name}" (${s.id}): a sample`));
    shipped.push({ id: s.id, name: s.name });
  }

  const layer = (name, text) => `@layer ${name} {\n${text.trim()}\n}\n`;
  write(
    join(out, "meridian.css"),
    `/* Open Meridian's plugin UI kit ${version} (open-meridian/meridian-ui).\n` +
      ` * Served by the dashboard at /.meridian/ui/${version}/ on every plugin host.\n` +
      ` * Colours come from the scheme (schemes/<id>.css); never write a raw colour. */\n` +
      "@layer meridian.scheme, meridian.tokens, meridian.base, meridian.components;\n" +
      '@import url("schemes/default.css") layer(meridian.scheme);\n\n' +
      read("generated/tokens.css") +
      "\n" +
      layer("meridian.base", read("src/css/base.css")) +
      "\n" +
      layer("meridian.components", read("src/css/components.css")),
  );

  write(join(out, "meridian.js"), read("src/meridian.js").replaceAll("__KIT_VERSION__", version));
  copyDir(join(ROOT, "src/lib"), join(out, "lib"), (f) => f.endsWith(".js"));
  copyDir(join(ROOT, "src/components"), join(out, "components"), (f) => f.endsWith(".js"));
  write(
    join(out, "scheme-contract.json"),
    JSON.stringify({ kit_version: version, ...contract, schemes: shipped }, null, 2) + "\n",
  );
  write(join(out, "gallery.html"), read("src/gallery/gallery.html").replaceAll("__KIT_VERSION__", version));
  copyDir(join(ROOT, "src/gallery"), join(out, "gallery"), (f) => f !== "gallery.html");

  console.log(`build OK: dist/${version}/ (${shipped.length} schemes: ${shipped.map((s) => s.id).join(", ")})`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
